
CREATE TABLE IF NOT EXISTS user
(
    id              varchar(36) not null,
    name            varchar(150) not null,
    email           varchar(150) not null UNIQUE,
    password        varchar(256),
PRIMARY KEY(id)
);

CREATE TABLE IF NOT EXISTS user_phone
(
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1, INCREMENT BY 1),
    number          varchar(50) not null,
    city_code       smallint not null,
    country_code    smallint not null,
    user_id         varchar(36) not null,
PRIMARY KEY(id)
);


ALTER TABLE user_phone ADD CONSTRAINT FK_user_userphone
  FOREIGN KEY (user_id)
  REFERENCES user(id);